### ISSUE TITLE
Implement filtering inside database queries

### ISSUE THREAD

**Issue by TWEApol** [RUGSoftEng/2018-PyDash.io#102]
Currently the ZODB database (upon which our own database layer `MultiIndexedCollection` relies) does not allow for applying filters to search queries, where the attribute(s) used in the filter is not a primary key. (e.g. search for all Dashboards with a certain `user_id`)

One way to accomplish this would be to alter the `MultiIndexedCollection` to have a second kind of key that allows for duplicates.

**Comment by Qqwy** [comment]
I'll work on this, I think. It won't be finished before Tuesday though, because other issues take higher precedence. :-)
