### ISSUE TITLE
Vastly improve Aggregators

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#105]
I have a wonderful idea to make the aggregators a whole lot quicker, and to be able to work right away on different resolutions of time-sensitivity, as well as being able to respond quickly to arbitrary start- and end-times for certain queries:

We can store aggregators in a tree-like structure:
- We have one 'root' aggregator for 'all time'.
- The 'root' aggregator contains a dict of years -> 'year' aggregators.
- Each 'year' aggregator contains a dict of months -> 'month' aggregators.
- Each 'month' aggregator contains a dict of day -> 'day' aggregators.
- Each 'day' aggregator contains a dict of hour -> 'hour' aggregators.
- Each 'hour' aggregator contains a dict of minute -> 'minute' aggregators.
- Each 'minute' aggregator contains a dict of second -> 'second' aggregators.

And this is where we stop; the bottom-most ones only contain a list of EndpointCalls. (or whatever data we'd like to store).

Note that there is no 'week' layer. This is for the simple reason that weeks are not equally divisible inside months (many months contain partial weeks), making them a bad target to use in this way. Instead, to query for weeks, we'll need to move down to the 'days' layer and combine the results of each consecutive seven days to form weeks.

(In the same manner, we can use ranges like '15 minutes', 'quarter years', etc.)

If the operations that combine two aggregators are reversible, then altering one of the contained aggregators can be done in O(1):

This means that when an 'hour' aggregator receives a new EndpointCall whose time falls in its '59th' minute, it will:
- first subtract the aggregator corresponding to the 59th minute from its own aggregated values.
- Then append the EndpointCall to that 'minute' aggregator.
- Then add the (now updated) 59th minute aggregator to its own aggregated values.

This means that on each layer, the addition operation is O(1), which means that in total, we have an O(log(n)) operation. (With n being `6` because that is the max. height of this tree)
Some examples of reversible operations: 
- sums (totals)
- multiplications (these are uncommon)
- averages (totals / count of results; the division step can be done when presenting the output.)
- min
- max

However, some results, are _not_ reversible. An alternative that even allows these operations to be fast, is to store all children one layer lower in a subtree of intermediate results themselves, allowing you to re-calculate results even more granularly. (Making each of these operation O(log(n)) where n is the number of siblings): In above example, we could re-use the output of the first half hour, the third quarter hour, etc., only requiring the combination of five separate results, rather than sixty). 

Querying for a range that happens to co-incide with one of these (very common) sizes, is a super-fast operation operation, because we can just return all aggregators of the specific size that fall in the specific range (to whose edges we can quickly zoom in because of the subdivision `year/month/day/hour/minute/second`).

Querying a for a range using a unit that is a multiple of one of these (like 'weeks == 7 days'), we can combine groups of adjacent values after we've extracted them in above manner, which still results in an O(n) algorithm.

What would make querying of subranges even faster, if we'd use [SortedDict](http://www.grantjenks.com/docs/sortedcontainers/sorteddict.html) instead of Python's built-in dict. (Or rather even: Build a 'defaultdict' wrapper around this one, so empty children are initialized as new empty aggregator objects automatically).

**Comment by Qqwy** [comment]
There's some information we'll have to re-compute separately on each layer I think, however, and that is a bit sad: Things like information about the `90th percentile`: This means you exclude the 10% slowest EndpointCalls from your aggregation, but the only way to find out what the 10% slowest (or the 90% fastest) are is by looking at _all_ of them in your range, rather than combining subranges. And if one EndpointCall falls in this range or not also changes based on EndpointCalls that are added to the system later...

nevertheless, this statistic is very valuable. I'll think more about a way to do this

**Comment by Qqwy** [comment]
... Good morning!

The approach I outlined in my first post is nice... if new EndpointCalls were added into the collection in any place, rather than only ever at the end (the 'newest' part).

So, it is a lot less of a hassle (and a lot simpler to comprehend) to just have a collection of dicts, one per granularity (year/month/day/hour/minute/second), and add a newly incoming EndpointCall to the latest Aggregator in each of these side-by-side. In this approach, keeping track of weeks is also simply possible, because we are not using data from the previous layer in the next one. (The time complexity is still the same as above!)

Now, to work with things like the `90th percentile` and similar metrics, an Aggregator will keep EndpointCalls internally in a SortedList (sorted by the response_time). At every EndpointCall insertion, we can see, for each of a couple of cutoffs (lowest10%/highest 90%, lowest-25%/highest 75%, lowest-50%/highest 50%, lowest 75%/highest 25%, lowest 90%/highest 90%) if it would fall to the left or right of  it.

We will then keep track of a couple of statistics separately for each cutoff point (besides one for 'overall'). For every addition, we only need to alter the statistics of one of the two branches of each cutoff, since the to-be-added EndpointCall either falls above or below it.

In this way we now have an on-line algorithm that works with these response-time based cutoffs as well.

**Comment by Qqwy** [comment]
Having looked more into this, it turns out there is a nice technology known as `t-digest` which only stores the 'interesting' points that create a graph, and therefore these are combinable from low-level to high. Very cool stuff.

There are a couple of Python-libraries that expose these. We should try them out.

**Comment by Qqwy** [comment]
https://dataorigami.net/blogs/napkin-folding/19055451-percentile-and-quantile-estimation-of-big-data-the-t-digest

^ Great explanation on how this works.

My idea now is as follows:

- Have one Aggregator-object per desired time granularity.
- Each of these contains a list of EndpointCalls, and maintains a set of scores:
  - count of the No. of EndpointCalls
  - Sum of certain values (like the response time)
  - Set of unique values (like unique visitors)
  - Average response time (summed response time / count)
  - T-digest which takes the response times as input, which allows us to calculate:
    - the median response time
    - the 90th-percentile response time
    - the 99th-percentile response time.


Because the original document by Patrick also would like us to track information per user, the 'set of users' (identified by the `group_by`-field that the flask-monitoring-dashboard API returns) could also be implemented as a dict where the `group_by` values are the keys (and directly also function as 'set'), with the values again being a list of EndpointCalls with again all (other) above statistics.


So I think it would be nice to split the `Aggregator` into multiple objects:

### 1. An AggregatorGroup object containing:
  - an overall `TemporalAggregatorsGroup`.
  - a dict of `IP-address` -> `TemporalAggregatorsGroup`
  - a dict of `group_by` -> `TemporalAggregatorsGroup`

### 2. A TemporalAggregatorsGroup
This contains, for each of the different desired granularities (minute, hour, day, month, year) a sequence of `Aggregator`s and dispatches to the correct one(s).

This object's purpose is to take an incoming EndpointCall and distribute it to the proper internal Aggregators so they can calculate the required statistics. It is also the object you can later query for specific data.

### The Aggregator
Contains:
- A list of stored EndpointCalls
- The statistics outlined above:
  - count of the No. of EndpointCalls
  - Sum response times
  - Set of unique visitors (IP)
  - Set of unique `group_by` values
  - Average response time (summed response time / count)
  - T-digest which takes the response times as input, which allows us to calculate:
    - the median response time
    - the 90th-percentile response time
    - the 99th-percentile response time.

Note that the aggregators themselves keep track of the two sets as well: In the aggregators that are specialized to a certain IP, obviously its set of IPs will only contain the trivial one IP-address. I don't think this is a problem and rather keeps the code re-usable.

**Comment by Qqwy** [comment]
Also, if you have better names for these things, please do propose them :grinning:

**Comment by Qqwy** [comment]
Results discussion:

- Good idea to set it up like this
- First update the Aggregator in Sprint No. 4, do temporal stuff in Sprint No. 5
- Only keep minutes-resolution for the last two weeks because it is a lot of data and that high of a resolution is not that necessary for longer times.

**Comment by Qqwy** [comment]
We'll talk about is this afternoon. (2018-05-06)

**Comment by TWEApol** [comment]
I was too hasty with my PR and didn't implement a proper TemporalAggregatorsGroup yet. In any case, querying a date range is impossible right now, and we would very much like this to be a thing.
