### ISSUE TITLE
Check whether `pydash_app/fetching/dashboard_fetch.py` should be refactored

### ISSUE THREAD

**Issue by TWEApol** [RUGSoftEng/2018-PyDash.io#107]
In the `backend/periodic_fetching` branch, the functionality to add the action of fetching endpoint calls and updating a dashboard to a task scheduler was added. This, however, made the file relatively large, which might indicate that it is wise to split the file in terms of functionality.

Note that the original choice of adding those functionalities to that file was because private methods were needed in the implementation of said functionalities.

**Comment by Qqwy** [comment]
After investigating the file, the number of lines is mostly caused by the documentation. It seems fine to me, lengthwise ;-)
