### ISSUE TITLE
Show account info in dashboard

### ISSUE THREAD

**Issue by dunnkers** [RUGSoftEng/2018-PyDash.io#116]
Accompanied with issue #115 which the back-end is going to implement. Tracked in branch [frontend/username-in-sidebar](https://github.com/RUGSoftEng/2018-PyDash.io/tree/frontend/username-in-sidebar). Currently looks like this:

<img width="218" alt="screen shot 2018-04-05 at 12 00 33" src="https://user-images.githubusercontent.com/744430/38359619-2e19ff5e-38c9-11e8-8836-00d86969c54b.png">

→ Should still display actual username though.

**Comment by dunnkers** [comment]
Better colors:

![Uploading Screen Shot 2018-04-05 at 12.09.13.png…]()

**Comment by Qqwy** [comment]
Commit that fills in username has been pushed.

Maybe it can be done even better by using cookies to keep track of _if_ someone is currently signed in and who that is, rather than passing it from login to dashboard in the way I'm currently doing, but still.

**Comment by InputUsername** [comment]
I've made a PR to return user info after logging in (#119)
