### ISSUE TITLE
Elaborate on Frontend Tech-stack in Architecture document

### ISSUE THREAD

**Issue by dunnkers** [RUGSoftEng/2018-PyDash.io#129]
As Patrick said in the meeting; update the Architecture document to include a section talking about the frontend stack, like as in the presentation.

**Comment by Qqwy** [comment]
@dunnkers Was this what you pushed at 12:30 in PR #132 ? Or is there even more you want to write in there?

**Comment by Qqwy** [comment]
(If not, this one can be closed)

**Comment by dunnkers** [comment]
ah yes it is! forgot to close this one

**Comment by Qqwy** [comment]
Actually, looking through the document right now, it seems that you copied+pasted some piece of text from some online website (without even removing the text formatting).

I'd suggest writing this text in your own words.

Also, you might elaborate on the usage of:

- material-ui
- axios
- nivo (which renders the graphs)

**Comment by dunnkers** [comment]
In fact , I used the formatting as I used in my presentation slides. Further, taking the explanations of the tools from their respective GitHub pages would tell nearly the same  explanations as I'd write myself, but if we want to I can rewrite them.

**Comment by dunnkers** [comment]
@Qqwy opened a PR for this: #142
