### ISSUE TITLE
Improve error handling for fetching functionality

### ISSUE THREAD

**Issue by InputUsername** [RUGSoftEng/2018-PyDash.io#135]
Currently error handling is non-existent, `None` is returned in case of a request error.

This would preferably be done in combination with #79 (logging).

In `flask_monitoring_dashboard_client`:
- [x] Extend logging to all functions
- [x] Handle incorrectly formatted JWT responses
- [x] Handle non-200 response codes:
  - [x] `get_details`
  - [x] `get_monitor_rules`
  - [x] `get_data`

In `pydash_app.dashboard.services.fetching`:
- [x] Use proper logging
- [x] Handle correctly the exceptions raised by `flask_monitoring_dashboard_client` functions
  - [x] `fetch_and_add_endpoints`
  - [x] `fetch_and_add_historic_endpoint_calls`
  - [x] `fetch_and_add_endpoint_calls`
- [x] Add some form of status flag/message to the `Dashboard` entity, so that the dashboard status can be returned from the backend API
  - Implemented using a `DashboardState` enum, which is used in the `Dashboard.state` property, in addition to a `Dashboard.error` string (which could be returned from the backend API)

What remains is to test the error handling under several conditions:
- [x] No internet connection
- [x] Remote dashboard configured to refuse connection
- [x] 300 responses (eg. by hosting the dashboard at `/real/dashboard` and redirecting there from `/dashboard`)
- [x] 400 errors
- [x] 500 errors
- [x] Malformed JSON Web Token response from `/get_json_monitor_rules`
- [x] Malformed JSON Web Token response from `/get_json_data`
- [x] Malformed JSON response
  - [x] in the JWT `data` field for `/get_json_monitor_rules`
  - [x] in the JWT `data` field for `/get_json_data`
  - [x] in the request body for `/get_json_details`

**Comment by Qqwy** [comment]
said by @InputUsername in #177:
> I would like to implement this using proper exceptions (also for the other functions in flask_monitoring_dashboard_client), which is why I created issue #135
