### ISSUE TITLE
Implement account creation

### ISSUE THREAD

**Issue by i32enrea** [RUGSoftEng/2018-PyDash.io#147]

**Comment by Qqwy** [comment]
We need more information in this issue.

**Comment by i32enrea** [comment]
Ok then, tomorrow in the meeting we will split this in two issues. I still don't know how to do it but I am working on it 😄

**Comment by i32enrea** [comment]
It'll be a sign up form based on this tutorial https://www.w3schools.com/howto/howto_css_signup_form.asp

**Comment by TheVeggydude** [comment]
@i32enrea @Qqwy It currently does not work on my local installation using `./build_and_run.sh`. And by that I mean that everything except for the user creation works. Issues are:

- [ ] The password verification field does not do anything 
- [ ] and as soon as you start type in that field the first password field becomes only one character long
- [ ] You can press the `register` button even when not everything is filled in.
- [ ] When having registered, I cannot log in using the credentials filled in.

**Comment by i32enrea** [comment]
Ok, I am trying now build and run and the fields you mention don't work properly, however they do work using yarn start. I am going to work on that and I will inform you asap

**Comment by i32enrea** [comment]
@TheVeggydude now a message comes up if either the username nor the password are filled in

**Comment by i32enrea** [comment]
Ok issue gone things are like this so far
![may-01-2018 12-29-55](https://user-images.githubusercontent.com/31631049/39469977-6bd84d10-4d3b-11e8-8621-685eb6cecaf3.gif)

**Comment by i32enrea** [comment]
@TheVeggydude the password one character issue is gone

**Comment by i32enrea** [comment]
@TheVeggydude When trying to register the new user I get a 405 error
