### ISSUE TITLE
Implement Continuous Integration (CI)

### ISSUE THREAD

**Issue by TheVeggydude** [RUGSoftEng/2018-PyDash.io#149]
- [x] Write tests.
- [x] Connect Travis to repo
- [x] Write `.travis.yml` config

**Comment by Qqwy** [comment]
Is it possible to split this into two issues? One for the deployment, one for the Continous Integration?
I think they are both large-scope issues that do not have a tremendous amount of overlap.

**Comment by TheVeggydude** [comment]
Done

**Comment by Qqwy** [comment]
https://github.com/Qqwy/python-multiple_indexed_collection <- Look into here for some other testing stuff.
