### ISSUE TITLE
Update .gitignore with React.js components

### ISSUE THREAD

**Issue by TheVeggydude** [RUGSoftEng/2018-PyDash.io#15]
Our .gitignore now mostly just ignores python and pycharm things. This should also include React.js.

**Comment by dunnkers** [comment]
In our [front-end branch](https://github.com/RUGSoftEng/2018-PyDash.io/tree/frontend/react-blueprint), we created a subfolder called [`pydash-front`](https://github.com/RUGSoftEng/2018-PyDash.io/tree/frontend/react-blueprint/pydash-front) which has a `.gitignore` file on its own. We maintain stuff we want to ignore on the frontend there - git supports `.gitignore` files in subfolders.
