### ISSUE TITLE
Implement account creation API route

### ISSUE THREAD

**Issue by InputUsername** [RUGSoftEng/2018-PyDash.io#150]
The frontend account creation feature needs to be supported by an API call to the backend

**Comment by Qqwy** [comment]
I suggest splitting this into two issues, because 'creation' and 'deletion', while related, are two different pieces of functionality. :-)

**Comment by InputUsername** [comment]
Sure, I just created this analogous to the frontend issue 😄

**Comment by TWEApol** [comment]
- [x] Write basic implementation using only username and password.
- [ ] Add email verification.

**Comment by InputUsername** [comment]
@TWEApol I think this issue can be closed? I'll create a new issue for email validation.

**Comment by TWEApol** [comment]
Alright, good plan.
