### ISSUE TITLE
fixing 404 error when logging in 

### ISSUE THREAD

**Issue by i32enrea** [RUGSoftEng/2018-PyDash.io#151]

**Comment by Qqwy** [comment]
It would be nice if this issue were to be updated with more information.

- What is the current behaviour
- What is the expected behaviour
- What do you expect is its cause?

**Comment by i32enrea** [comment]
I cannot use flask seed after that if I try to flask run the app it does not let me log in properly showing a black page. Here I attached you screenshots of what I see. I am asking for help to solve it. Thank you 
<img width="1677" alt="screen shot 2018-04-21 at 19 37 28" src="https://user-images.githubusercontent.com/31631049/39087074-77973352-459b-11e8-96c3-7f6036f49e34.png">
<img width="1449" alt="screen shot 2018-04-21 at 19 37 56" src="https://user-images.githubusercontent.com/31631049/39087080-853f424c-459b-11e8-8d08-d3d987560131.png">


<img width="1477" alt="screen shot 2018-04-21 at 19 36 01" src="https://user-images.githubusercontent.com/31631049/39087060-445edb0c-459b-11e8-8cc6-3ceb01d97784.png">

**Comment by InputUsername** [comment]
@i32enrea The error on the right in the last screenshot is caused because you are not running a local testing flask app + dashboard; I will fix this (#155)

**Comment by i32enrea** [comment]
Flask seed works now, however when logging in, the dashboard page remains empty

**Comment by InputUsername** [comment]
Empty, as in a white page? Or the UI does show up, but no dashboards?

**Comment by Qqwy** [comment]
For now, remove the protected routes stuff. Later, we'll try to protect the other paths in a different way.

**Comment by Qqwy** [comment]
Will be fixed once #193 is built; closing this one as it does not contain more information.
