### ISSUE TITLE
Add some new visualisations

### ISSUE THREAD

**Issue by ArjanTilstra** [RUGSoftEng/2018-PyDash.io#152]
- [ ] Create endpoint-specific pages
- [ ] Create more specific API routes for individual endpoints/points of data
- [ ] Add visualisations such as execution time, times accessed, accessed by IP, etc.

**Comment by Qqwy** [comment]
We need more information in this issue.

- What do you/we want to have added where?

**Comment by Qqwy** [comment]
This issue should be made more specific.
