### ISSUE TITLE
Split pydash_app.impl.fetch to make dashboard fetching testable

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#154]
Currently `pydash_app.impl.fetch` (which is used by `pydash_app.fetching.dashboard_fetch.py`) contains a combination of both remote-request logic as well as serialization/deserialization logic.

It would be good to split this and let `pydash_app.fetching.dashboard_fetch.py` work with dependency-injection of the 'fetcher' to use, to make it more testable.

(Rather than spinning up a 'test server' with real socket connections, which is error-prone, a lot of work and slow, we can then skip the whole request/response part and simply return the expected requests right away without doing HTTP stuff).

**Comment by InputUsername** [comment]
What exactly do you mean by serialization logic? Remote dashboards return (most) data encoded using JWT. The functions in `pydash_app.impl.fetch` simply request from the remote dashboard and decode. Functions in `pydash_app.fetching.dashboard_fetch` then use these functions to turn the data into `Endpoint`s etc.

If I understand you correctly, you want to be able to swap this out for functions that just return some static data: wouldn't this be possible by having a separate module with the same function prototypes?

**Comment by InputUsername** [comment]
Side note: it's probably a good idea to do this before #135 and #136

**Comment by InputUsername** [comment]
Fair enough :-) Although I'm not sure how useful testing the decoding would be, since it is simply a call to `jwt.decode`, and PyJWT seems to be very well tested.

**Comment by Qqwy** [comment]
Turns out that `requests` already has been buid in an adaptable way, and that there is a `requests-mock` package we could use:

http://requests-mock.readthedocs.io/en/latest/mocker.html

**Comment by Qqwy** [comment]
(So just using that would be smarter than building/re-inventing this stuff manually)
