### ISSUE TITLE
Implement account deletion API route

### ISSUE THREAD

**Issue by InputUsername** [RUGSoftEng/2018-PyDash.io#161]
The frontend account deletion feature needs to be supported by an API call to the backend

**Comment by TWEApol** [comment]
When deleting a user, should all connected dashboards (that only have one remaining connected user) be deleted as well?

**Comment by InputUsername** [comment]
Yes, I think that's a good idea.

**Comment by Qqwy** [comment]
Yes, remove the dashboards. If someone wants to re-create an account later, we just refetch everything.
