### ISSUE TITLE
Implement email verification for account creation

### ISSUE THREAD

**Issue by InputUsername** [RUGSoftEng/2018-PyDash.io#179]
See the discussion between @Qqwy and me here: https://github.com/RUGSoftEng/2018-PyDash.io/pull/153 for clues on how we might implement this.

Basically:
- After sign up, put the new account in a "waiting for confirmation" state.
- Generate a long random alphanumeric string ("confirmation token") and assign it to the user.
- Send an email with a confirmation link including the token.
- (At some point, support re-creating the token and re-sending a confirmation mail)
- Clicking the confirmation link takes the user to a page that may or may not be handled by the React app. I think having the React app handle the confirmation is better: no API route exposed in the email, and the React app can more easily redirect to the login page/show flash messages/etc.

**Comment by InputUsername** [comment]
We have decided to leave out the frontend and actual email sending parts for now, since these require a lot more work and are not feasible to complete. However, we will implement points 1, 2, and an API route to "confirm" a user, as well as limiting other API routes to "confirmed" users only.

**Comment by TWEApol** [comment]
For now my implementation works as follows:
- The successful registration response now also (temporarily) includes a 'verification_code' field, such that the front-end can display this to the user (for the time being).
- The `/api/user/verify` route requires the user to be logged in. This is to make sure we don't have to search for the user by verification code, as well as making sure only the user can verify their account. However, this also means more hassle for the user, as well as more work for the front-end and a less neat application design (users can log in, but almost every other backend api-route is barred off [i.e. users can still delete their account and log out]).

**Comment by Qqwy** [comment]
Decision:

- Logging in only possible if verified
- Verification is possible without logging in, (and obviously only once).
- When attempting to log in while not verified, show special error message on loging screen.
