### ISSUE TITLE
Dashboard states as actual Python Enum

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#190]
The new Dashboard as Finite-State-Machine change (#186 ) is wonderful!

It would however be very nice from a readability/maintainability point-of-view to actually use a Python Enum for the different states: 

https://docs.python.org/3/library/enum.html

**Comment by InputUsername** [comment]
Is it not already using an `enum.Enum`?

**Comment by InputUsername** [comment]
Oh, I did not think of naming the enum members in all caps.

**Comment by Qqwy** [comment]
I apologize; while looking in the diff yesterday evening it seemed like the different enum variants were top-level integers, rather than part of the `DashboardState` Enum.

I browsed the code locally just now. Looks really good! :+1:

**Comment by InputUsername** [comment]
OK, I'll leave it like this, newer Python documentation uses lower case as well :smile:
