### ISSUE TITLE
Find username after refreshing while logged in

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#193]
This issue concerns both back-end and front-end.

I'm not sure how to do this cleverly, but we need to find a way to do this.

Right now, when you log in and refresh, the front-end has no way to look up the username anymore, and it will not be shown in the menu.

**Comment by InputUsername** [comment]
Is there a way to cache it locally after logging in?

Regardless, `/api/login` returns user info when the user logs in successfully, or is already logged in. Maybe that is useful?

**Comment by Qqwy** [comment]
Caching it locally would be possible, but would not be in sync with how long a session on the back-end remains alive, so from time to time there would be errors there.

After giving this a little more thought, an `/api/is_logged_in` that returns the username if we are logged in and an error if not, would be very useful.

We can call that endpoint when we load the app for the first time, and use it to redirect to the login-page if necessary. That would also fix the 'Protected Page' nonsense.

**Comment by InputUsername** [comment]
Hmm, the functionality of `/api/is_logged_in` is already provided by `/api/login`: if you're logged in according to `Flask-Login`, it returns a 200 OK. Do you think it would be useful to have this extra route?

**Comment by ArjanTilstra** [comment]
I think this can be easily done using a componentDidMount() function in the MainInterface class, simply by calling the login function again and updating the username in the State. Is there anything wrong with that approach?

**Comment by Qqwy** [comment]
@InputUsername We need to re-supply a username and password to `/api/login`, right? We do not have those lying around when the page is refreshed. Unless we keep those in cookies, which seems like a very bad idea security-wise.

@ArjanTilstra Indeed, calling the new API route from there is what I had in mind exactly :smile: .

**Comment by InputUsername** [comment]
@Qqwy no username/password needed, just the session cookie of a logged in user. Or are you referring to the situation where the cookie expires/does not exist when you refresh?

**Comment by Qqwy** [comment]
`/api/login` returns the proper information when you already have the cookie.
