### ISSUE TITLE
Backend API Request: Boxplots for endpoints

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#195]
I'd like to show a list of boxplots, one per Endpoint as a graph in the front-end, similar to what the Flask-Monitoring-Dashboard does.

For this I need and API endpoint that:

- Returns a list of Endpoints, where each element contains:
  - name of the endpoint
  - average response time
  - fastest measured response time.
  - fastest quartile (25 percentile) response time
  - slowest quartile (75 percentile) response time
  - 90th percentile. response time
  - 99th percentile. response time
  - highest measured response time.

We'll make a list of boxplots, or a list of stacked bars of this data.

**Comment by TWEApol** [comment]
With `response time`, do you mean `execution time`? The current FMD displays execution time instead of response time, and as far as I know we cannot discern what the response time was.

**Comment by TWEApol** [comment]
Also, aren't `fastest measured response time` and `highest measured response time` the same thing?

**Comment by InputUsername** [comment]
@TWEApol I think it should be `lowest measured execution time` (ie the fastest execution).

**Comment by TWEApol** [comment]
Furthermore, wouldn't you also need to have the 50 percentile in order to complete the boxplot?
