### ISSUE TITLE
Create tabs to access endpoint page (2)

### ISSUE THREAD

**Issue by LarsDoorenbos** [RUGSoftEng/2018-PyDash.io#211]
Best done from dashboard page, maybe temporarily from sidebar

**Comment by Qqwy** [comment]
I like the idea to use a list for this similar to what the FMD does. In this list we can provide some basic information about each endpoint already.

**Comment by Qqwy** [comment]
Outcome of meeting discussion:

- On top of Dashboard page, have tabs.
- One tab for the dashboard's measurements (graphs)
- One tab for the Dashboard's endpoints (which will the page this issue describes)
- One tab for the Dashboard's settings.
