### ISSUE TITLE
Personal profile edit page links (1)

### ISSUE THREAD

**Issue by i32enrea** [RUGSoftEng/2018-PyDash.io#213]
When clicking on the usericon on the sidebar we will be redirected to a personal page which will also have a link to delete account among others options

**Comment by Qqwy** [comment]
Creating the settings page is #242 
Creating the menu links is this issue:

- [ ] Username
- [ ] 'Settings' item with gear icon.

**Comment by LarsDoorenbos** [comment]
Isn't the settings menu item already implemented? Or am I reading this wrong?
