### ISSUE TITLE
Account Deletion (5)

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#215]
Second half of #147 .

Depends on #242

**Comment by i32enrea** [comment]
I was thinking about implementing an user setting which if you click on it, it asks you if you are sure to erase your account, if you click no nothing happens and if you click yes, it will log out, erase the acocunt from the database and redirect to "/"

**Comment by Qqwy** [comment]
The button should be on the `settings` page, and the confirmation window should ask the user for the password (and this should be sent to the API endpoint `/user/delete`)

**Comment by i32enrea** [comment]
- [ ] Pop-up
- [ ] Deletion form
- [ ] Warning message saying this is permanent
