### ISSUE TITLE
Create notification bar (3)

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#227]
There are now multiple places in which we want to show notifications to the user in the interface once something has been done.

For this, we need to create a system to show these notifications. Material-UI contains a so-called ['Snackbar'](https://www.material-ui.com/#/components/snackbar).

This is probably done in the easiest way by using something like this package: https://github.com/TeamWertarbyte/material-ui-snackbar-provider because messages are shown when state _changes_.

---

**This issue is about adding the Snackbar itself, and not the separate messages; those will be separate issues.**

**Comment by i32enrea** [comment]
This is how things are going so far. Later today I will implement it into the login page.
![may-04-2018 11-25-17](https://user-images.githubusercontent.com/31631049/39621139-f48e9d90-4f8d-11e8-8d71-0e5620926a72.gif)

**Comment by Qqwy** [comment]
@i32enrea The PR of this was merged? Can this issue be closed, or am I mistaken?
