### ISSUE TITLE
Tabs for graph times  (3)

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#237]
Create tabs (https://material-ui-next.com/demos/tabs/#basic-tabs) above each graph to switch between viewing:

- [x] last hour
- [x] last day
- [x] last week
- [x] last month
- [x] last year
- [x] all time

(For now, 'hour' is default; this might be changed per-graph depending on what we decide on as whole team + customer).

The 'data fetching' component should thus become a subcomponent of the tablist, and each of these should send to the API a `time_view` argument (one of `hour`, `day`, `week`, `month`, `year`, `all_time`). That stuff is not implemented in the back-end yet so all graphs will look the same for now, but they can easily do that once we have this in place :-).

**Comment by i32enrea** [comment]
@Qqwy Could you take care of this issue? I am struggling a bit with the user settings form
