### ISSUE TITLE
Add support for dashboard names to the backend and API

### ISSUE THREAD

**Issue by InputUsername** [RUGSoftEng/2018-PyDash.io#238]
- Dashboard should get a name field
- The /dashboards and /dashboards/:dashboard_id call should return this name in the responses.
- In the Dashboard update API endpoint, the name should be configurable.

**Comment by Qqwy** [comment]
In how far is this issue solved by #245  ?

**Comment by InputUsername** [comment]
Apart from the Dashboard update API endpoint (which doesn't exist) it's finished
