### ISSUE TITLE
User settings form (5)

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#242]
The user settings page is still empty.

It should contain a form to alter:

- [x] Username
- [x] Turn sounds on/off.
- [x] new Password (including a `new password confirmation field`).
- [x] Only when the password field is filled, is it required to enter the current password as well. This field should probably auto-show once someone attempts to alter their password.

There is no back-end API endpoint yet, but we should create a function where the actual call can be added to later. (and send a console message with the entered information in there).

**Comment by i32enrea** [comment]
I am going to implement the settings form using react-settings-pane https://www.npmjs.com/package/react-settings-pane

**Comment by InputUsername** [comment]
What would you guys like to see in the backend api?

My suggestion would be something like `/user/settings/change`, where you can send a JSON object, passing the fields you want to update/change.

**Comment by i32enrea** [comment]
@InputUsername I like the idea, is the API ready to support password update?

**Comment by i32enrea** [comment]
I am going to uses expansion panels where I will locate the forms to update the info, or switch off the sounds

<img width="1680" alt="screen shot 2018-05-03 at 13 50 24" src="https://user-images.githubusercontent.com/31631049/39574966-303cc50c-4ed9-11e8-977a-d395c9778354.png">

**Comment by i32enrea** [comment]
I am also getting information from http://www.thegreatcodeadventure.com/react-redux-tutorial-part-vi-the-edit-feature/

**Comment by InputUsername** [comment]
@i32enrea there's no API call yet, I'll make an issue for that

**Comment by i32enrea** [comment]
According to Patrick's suggestion, the new form will only have one OK button which depending on the filled Textfield, it will trigger a different api call.
<img width="1679" alt="screen shot 2018-05-28 at 10 57 31" src="https://user-images.githubusercontent.com/31631049/40606592-24812c3a-6266-11e8-95ac-3ad992720aee.png">
