### ISSUE TITLE
Email verification - Re-generating expired verification codes, periodically removing zombie users

### ISSUE THREAD

**Issue by TWEApol** [RUGSoftEng/2018-PyDash.io#280]
In order for users to still be able to verify their accounts after their initial verification code has expired, they should be able to choose to generate a new verification code.
However, in order to keep the amount of 'zombie' users that haven't been verified in a long time after receiving an email, all users should be checked periodically. The current proposal is to delete such users after 30 days. It should suffice that the check be performed once a day.

**Comment by InputUsername** [comment]
This issue has been merged into #312.
