### ISSUE TITLE
Research how to format JSON data (Json.api)

### ISSUE THREAD

**Issue by ArjanTilstra** [RUGSoftEng/2018-PyDash.io#30]
Find out relation between redux and json.api.

**Comment by dunnkers** [comment]
Hint: take a look at [redux-json-api](https://github.com/redux-json-api/redux-json-api

**Comment by Qqwy** [comment]
I'd like to comment that it is highly probable that JSON-API is extreme overkill for our application, at least in its current state. I'd highly urge us to look for a simpler messaging data format for the MVP; we can always expand it to JSON-API later.

_(We'll discuss this during the meeting but I wanted to make sure that we have mention of it somewhere on paper)_

**Comment by dunnkers** [comment]
Makes sense. I remembered that JSON-api was quite simple back in the days, however looking at it now does look like an overkill. We could agree on an alternative spec.
