### ISSUE TITLE
Update Email Verification

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#312]
As @TWEApol said:
>In order for users to still be able to verify their accounts after their initial verification code has expired, they should be able to choose to generate a new verification code.
However, in order to keep the amount of 'zombie' users that haven't been verified in a long time after receiving an email, all users should be checked periodically. The current proposal is to delete such users after 30 days. It should suffice that the check be performed once a day.

So, to do are the following:
- [x] Changing timeout to 1 day
- [x] Removing old veritifcation codes (+ old unverified users)
- [ ] Regenerating verification codes on request

**Comment by InputUsername** [comment]
Point 1 has been implemented in `backend/user_verification`.

**Comment by InputUsername** [comment]
Point 3 will not be done; users that haven't verified before their code expires are simply removed and need to register again.
