### ISSUE TITLE
Aggregator problem

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#323]
When currently seeding, at the end, the dashboard aggregator's somehow is empty, which results in empty graphs.

The weird thing is that the contained endpoints _do_ have aggregators with proper data.

Also, manually adding endpoint_calls afterwards to the dashboard will add these to the aggregator (and these changes persist?)

**Comment by TWEApol** [comment]
The current temporary workaround for this has been to hardcode the four empty statistics in the aggregator itself. Actual bug fix will be investigated a.s.a.p.

**Comment by TWEApol** [comment]
I have removed the `HIGH-PRIORITY` label, as I we can build on top of the workaround I've made. I still don't know why this problem exists and why my workaround works, but I assume that the eventual fix won't be made much more difficult if we stay consistent with how we add statistics.
