### ISSUE TITLE
Implement autorefreshing after the user has changed something (e.g. edited setting/added dashboard)

### ISSUE THREAD

**Issue by TWEApol** [RUGSoftEng/2018-PyDash.io#330]
Currently the frontend does not refresh its displayed information after sending changes to the backend (e.g. by changing a user/dashboard setting or adding/removing dashboards)

**Comment by Qqwy** [comment]
Auto-refreshing after adding dashboard works!

This has been made nicer in PR #454.

**Comment by Qqwy** [comment]
Also, refreshing after changing user-settings works now.
