### ISSUE TITLE
Information next to fields in 'add new dashboards'

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#352]
so we know what we should enter, where to find the information to enter.

**Comment by InputUsername** [comment]
- The URL should be the full URL to the dashboard, ie. the domain + the dashboard link (without trailing slash)
  - the default dashboard link is `dashboard`;
  - a custom link can be configured in the user's Flask-MonitoringDashboard configuration file.
- The security token is configured in the Flask-MonitoringDashboard configuration, but (probably) not in the configuration file; rather, it is set after importing `flask_monitoringdashboard`, using `flask_monitoringdashboard.config.security_token`.
 - The default token (and other default configuration options) can be found here: https://github.com/flask-dashboard/Flask-MonitoringDashboard/blob/master/flask_monitoringdashboard/core/config/__init__.py
