### ISSUE TITLE
Registration hangs

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#353]
Not sure if this is a front-end or back-end issue, but currently when registering, the page hangs when clicking the 'register' button (with correct filled in information)

**Comment by TWEApol** [comment]
If #335 is resolved and this issue still persists, then this is most likely a frontend issue.

**Comment by TWEApol** [comment]
Update: whenever the backend responds (e.g. with a bad status code), the frontend still hangs.
