### ISSUE TITLE
Remove unnecessary collection of endpointcalls in Aggregator, Endpoint and Dashboard

### ISSUE THREAD

**Issue by TWEApol** [RUGSoftEng/2018-PyDash.io#363]
As far as I know, there is no point in collecting endpointcalls in the `Aggregator`, `Endpoint` and `Dashboard` classes. From my testing, these can be safely removed in terms of functionality of these respective classes. However, some logging (especially in fetching related methods) still use direct access to these private attributes.

**Comment by InputUsername** [comment]
The logging functionality can be replaced by simply printing the total number of endpoint calls in the aggregator instead of `len(dashboard._endpoint_calls)`.

**Comment by TWEApol** [comment]
While indeed it is the case that we can use `Aggregator.as_dict()['total_visits']` or something similar for this, a dashboard's aggregator is a private attribute as well.
What sounds more logical to me is to count the number of retrieved endpoint calls in the methods that actually do the fetching.

**Comment by TWEApol** [comment]
Note: we might want to stay clear of removing these collections for now, as they might prove to be useful in the future

**Comment by TWEApol** [comment]
Update: in the current state of the application, both `Endpoint._endpoint_calls` and `Dashboard._endpoint_calls` are useful. `Aggregator.endpoint_calls` still isn't used for anything yet.
