### ISSUE TITLE
Slightly restructure Flask application to use Blueprints, which solves circular dependency

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#37]
Currently, in `pydash_web/__init__.py`, there is a very odd circular dependency, because `pydash_web/routes.py` depends on the `flask_app`-object defined in this file while it also depends on routes.py:

`flask_app <- routes <- file setting up flask_app`

What would be nicer, as explained in the ['better application structure' chapter of the Flask tutorial](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xv-a-better-application-structure) (and also see: [Flask documentation's section about blueprints](http://flask.pocoo.org/docs/0.12/blueprints/)), is to let the routes work with a _blueprint_, and only instantiate the real Flask application from the outside-most part of our application:

`flask_app_blueprint <- routes <- file setting up flask_app`

This will also in the near future allow us to make changes during the testing environment, because we can delay the moment during which the flask application is made to actual app startup time, rather than the time during which we happen to include 'module X' in another file.

---

This issue is low-hanging fruit suitable to understand more about how a system built with Flask works, and as such I think it would be best if @TWEApol or @InputUsername would pick it up.

**Comment by InputUsername** [comment]
Fixed by #47
