### ISSUE TITLE
Fix all datetime formats to use ISO-8601 standard

### ISSUE THREAD

**Issue by TWEApol** [RUGSoftEng/2018-PyDash.io#404]
~~Exactly what's on the tin.~~

The issue is parts of my own code, I use a different format to specify datetime strings. (e.g. `2018-5-28 21-34-42` while elsewhere `2018-05-28T21-34-42` is used, where the latter one follows the ISO-8601 standard.) Furthermore, the front-end will be sending datetime strings whose format comply to the ISO-8601 standard.
The [ISO-standard](https://en.wikipedia.org/wiki/International_Organization_for_Standardization) is a well-respected international standard, so following it makes it less likely our code (both internally as well as externally) might run into different ways of formatting things.

**Comment by Qqwy** [comment]
> Exactly what's on the tin.

Don't do this; rather give some more explanation:

- why is this a problem?
- what is this ISO standard anyway? (You can link to Wikipedia from your Issue-post, you know)

I know I am giving possibly big feedback on something minor, but I have a lot of confidence in your SE and teamworking skills! :+1:

**Comment by TWEApol** [comment]
oops ._.
