### ISSUE TITLE
Backend API request: per-endpoint execution times boxplot

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#412]
I'd like to show a set of boxplots, one per endpoint in the frontend.

For this, I'd like to have a statistic endpoint from the backend that returns, per endpoint:

- the fastest execution time
- the faster 25 percent (quartile)
- the median execution time
- the slower 25 percent (i.e. 75th percentile)
- the 99th percentile.
- the slowest execution time

**Comment by TWEApol** [comment]
@Qqwy Should this return a collection of values for all endpoints in a dashboard, or should it only return the values of a specific endpoint on that dashboard?

**Comment by TWEApol** [comment]
Also, the `/api/dashboards/<dashboard_id>/endpoint_boxplots` route pretty much already does the former, so I'm not sure whether such a new endpoint is necessary.

**Comment by InputUsername** [comment]
Maybe you could split the existing route in a per-endpoint route?

**Comment by TWEApol** [comment]
I'm updating the existing route to return a dict (as well as some other minor refactoring) in order to make the output of our routes more uniform.
