### ISSUE TITLE
Think of a way to store secret tokens/keys securely

### ISSUE THREAD

**Issue by TWEApol** [RUGSoftEng/2018-PyDash.io#421]
Seeing as our entire codebase is opensource and our current approach of hardcoding in secret tokens/keys or grabbing them from environment variables, whose setup is also stored in a script file (e.g. `start_pipenv.sh` or `build_and_run.sh`), we should find a way to:
- Store them securely, such that no outsiders other than the maintainers/admins of PyDash.io can know and change them
- Share them securely with all maintainers/admins of PyDash.io
- Back them up securely, such that if the machine that runs the server goes down, this essential information is not lost.

**Comment by Qqwy** [comment]
follow up by #444
