### ISSUE TITLE
confirmation email has the wrong url in it

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2018-PyDash.io#439]
<img width="795" alt="screenshot 2018-06-05 16 17 14" src="https://user-images.githubusercontent.com/464519/40981741-fcc6c098-68db-11e8-93be-0544bfcc7938.png">

**Comment by TWEApol** [comment]
This fix for this is already up in PR #437

**Comment by InputUsername** [comment]
Fixed by #437.
