### ISSUE TITLE
Create actual JSON specification

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#44]

**Comment by Qqwy** [comment]
I took a little time to write out what we've established so far for the API using the Swagger API documentation tool.

The raw file can be found here:
https://raw.githubusercontent.com/RUGSoftEng/2018-PyDash.io/swagger_api/docs/frontend_backend_specification-swagger.yaml

And you can paste its content in the swagger editor (http://editor.swagger.io) or go to any place where swagger-ui is setup (their demo page is http://petstore.swagger.io) and paste above URL in the url-bar there to explore it.

**Comment by Qqwy** [comment]
[pydash.pdf](https://github.com/RUGSoftEng/2018-PyDash.io/files/1836106/pydash.pdf)
And here is a (not perfect, but close) PDF-render of said endpoint-paths.

This API-specification is thus not done yet, but it is a start.

**Comment by dunnkers** [comment]
Looks nice. We don’t actually get data for the dashboards yet?

**Comment by Qqwy** [comment]
Vergelijken spec van Swagger met daadwerkelijke backend app. @InputUsername

**Comment by InputUsername** [comment]
Fixed by #69
