### ISSUE TITLE
Security: Production server environment variables

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#444]
- [x] Move settings from build_and_run to server (create an `pydash.env` file and link it in the systemd startup file `/etc/systemd/system/pydash.service`)
- [x] Change email server password and other settings that are currently exposed in build_and_run and configuration files.

**Comment by InputUsername** [comment]
So far I've created a file `/etc/pydash/pydash.env` on the server to contain all environment variables that are used in production. Linking it and removing the old credentials still needs to happen.

**Comment by Qqwy** [comment]
First step is done.

Second step can hopefully someone of you do without my involvement ;-)

**Comment by InputUsername** [comment]
I will change the credentials
