### ISSUE TITLE
Move issues from minutes to GitHub Project

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#5]
Two parts:

- [x] Back-end issues that are outlined in the #backend channel in Slack.
- [x] Other issues that are part of the minutes of last meeting.

**Comment by Qqwy** [comment]
@ArjanTilstra How are the minutes coming along? If you share them, I will add the other general issues that are part of there. :slightly_smiling_face:

**Comment by ArjanTilstra** [comment]
The minutes are already in the google drive folder. I uploaded them yesterday. I'll send them on Slack as well.

**Comment by TheVeggydude** [comment]
Are there any issues left to put on GitHub?

**Comment by Qqwy** [comment]
I just looked through the minutes, and the few issues that were in the minutes of the meeting of 2018-03-05 have already been finished (bar my issue to add the non-functional requirements, which already existed as #11 ).

So this is done! :-)
