### ISSUE TITLE
Fix the API calls in the frontend

### ISSUE THREAD

**Issue by FlyingBird95** [RUGSoftEng/2018-PyDash.io#70]
The frontend requests /api/login/

But, this backand expects /api/login (without the /)

Can someone update the frontend?

**Comment by Qqwy** [comment]
I just fetched the latest development version and tried it out in FireFox, where it worked without any problems. 

Has this already been fixed in the meantime by someone else?

**Comment by InputUsername** [comment]
@Qqwy yes, #74 fixes this!
