### ISSUE TITLE
Protect restricted pages from logged out visitors

### ISSUE THREAD

**Issue by ArjanTilstra** [RUGSoftEng/2018-PyDash.io#87]

**Comment by InputUsername** [comment]
I've pushed a fix to always serve the React app from the backend to `backend/fix_404` so that going to `/dashboard` will serve the React app. However now the React app will happily show the dashboard (without info because you're not logged in).

**Comment by dunnkers** [comment]
When initiating the React app, it is not known whether a user still has a valid _session token_ in his cookies. Therefore I think it'd be nice to have a `/peek` endpoint, which we would simply send a message asking "_are we logged in?_". Then, for the rest of the React-app lifetime, we would locally store whether the user is logged in, and can correctly redirect the user to either the login page or the dashboard. So, an endpoint like

```
http://pydash.io/api/peek
```

(Will get back on the exact API spec later, which HTTP code etc.)

 So back-end, could one of you create such an endpoint?
@InputUsername @TWEApol @TheVeggydude @Qqwy 

P.S. If there is a smarter (easier) way of doing this, I'm glad to hear. BTW, even if you [store the session token in `localstorage`](https://stackoverflow.com/questions/47684338/how-to-check-if-a-user-is-logged-in-and-how-to-save-their-information-react?rq=1) then you still aren't sure whether it's actually valid.

**Comment by InputUsername** [comment]
Currently if you request `/api/login` without post data while already logged in, you should receive a 200 OK. I'll have to check if the backend correctly checks validity of the session though

**Comment by dunnkers** [comment]
@InputUsername ah that seems to do the trick! Will try to implement it that way.

**Comment by Qqwy** [comment]
Is this already done or not yet?

**Comment by dunnkers** [comment]
Not yet , it's a work in progress! 🚧

On 12 Apr 2018 15:31, "Qqwy" <notifications@github.com> wrote:

Is this already done or not yet?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/RUGSoftEng/2018-PyDash.io/issues/87#issuecomment-380805868>,
or mute the thread

**Comment by dunnkers** [comment]
Closed as of #144 is merged.
