### ISSUE TITLE
Bug: Reseeding DB after logging in results in KeyError when attempting to login again.

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#89]
Because the old user ID is still stored in the session, this ID is attempted to be looked up in the database which will fail with a KeyError since it does not exist.

But we should return a proper JSON-response in this case.

**Comment by Qqwy** [comment]
Should also automatically log this malformed user out

**Comment by InputUsername** [comment]
Where is the KeyError raised exactly? Do you have a traceback?

**Comment by Qqwy** [comment]
IIRC this one was fixed by a PR that was already merged. Closing this one!
