### ISSUE TITLE
Aggregation functionality

### ISSUE THREAD

**Issue by Qqwy** [RUGSoftEng/2018-PyDash.io#95]
The aggregation functionality will be a component that is used both by the Dashboard as well as (later on) the Endpoints it contains, so, (as discussed) it will be a separate class.

It maintains:
- an internal list of all API calls made thus far.
- a bunch of aggregate results.

It contains a function to add a new endpoint call response to it (which looks like this):

```json
{
        "execution_time": 1403.8760662078857,
        "endpoint": "index",
        "group_by": "None",
        "version": "1.0",
        "time": "2018-03-06 12:46:38.836649",
        "ip": "145.97.155.54"
    }
```

_(side note: I think it would be nice to wrap this call response in an object as well, by the way, because the data is quite normalized.)_

Adding this response, for now does the following:
- increment the internal count of endpoint responses (total visits)
- inside an internal dict of dates, increment the count of endpoint responses for the day in which `time` falls. (This should probably be a defaultdict that returns `0` for empty keys).
- Add the execution time to an internal 'total execution time' number, which can be divided by the number of total visits to get the average execution time.

- It should have functionality to return its internal aggregates in a similar format as the current fake JSON response.

**Comment by Qqwy** [comment]
Obv. this can be developed completely independent from the persistence stuff that @TWEApol  is working on; later on, this class will automatically persist as part of the Dashboard etc.

**Comment by InputUsername** [comment]
1. I believe @TWEApol is working on an `EndpointCall` class which wraps the endpoint call data
2. IIRC endpoint calls are now also stored in the dashboard and endpoint themselves, are we going to maintain it in both or only in the aggregator?
